# This file does not work by itself

version: '3.7'

services:
  django:
    image: hello_django
    restart: "no"
    expose:
      - 8000
    volumes:
      - static_data:/home/hello_django/static

  nginx:
    image: hello_django_nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: "on-failure"
    ports:
      # - HOST:CONTAINER
      - 80:80
      - 443:443
    volumes:
      - static_data:/home/hello_django/static
      - ssl_data_conf:/etc/letsencrypt
      - ssl_data_www:/var/www/certbot
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - django
      - certbot
  
  certbot:
    image: hello_django_certbot
    entrypoint: ["/bin/bash",  "/home/hello_django/setup.sh"]
    restart: "no"
    volumes:
      - ssl_data_conf:/etc/letsencrypt
      - ssl_data_www:/var/www/certbot
      - /var/run/docker.sock:/tmp/docker.sock

volumes:
  static_data:
  ssl_data_conf:
  ssl_data_www: