# docker-compose -f docker-compose.base.yml -f docker-compose.local.yml up --build

version: "3.7"

services:
  django:
    build: ./django
    container_name: hello_django_dev
    env_file:
      - ./django/development.env

  nginx:
    build: ./nginx
    container_name: hello_django_nginx_dev

  certbot:
    build: ./certbot
    container_name: hello_django_certbot_dev
    environment:
      DEV: "true"
      NGINX_CONTAINER: "hello_django_nginx_dev"
