# This is one step before pushing images to Dockerhub registry. Can be used in Github Actions.

# Test new build with Newman. Staging environment is fairly similar to development environment.
# This is done, so that live DB is not accidentally trashed with data. Also may be difficult 
# to access DB-server with Github's IP-Address. If any actual secret keys are still required,
# consider uploading these keys to Github-Secrets.

# Use with:
# docker-compose -f docker-compose.base.yml -f docker-compose.staging.yml up --build

version: '3.7'

services:
  django:
    build: ./django
    container_name: hello_django_stage
    env_file:
      - ./django/staging.env

  nginx:
    build: ./nginx
    container_name: hello_django_nginx_stage
  
  certbot:
    build: ./certbot
    container_name: hello_django_certbot_stage
    environment:
      DEV: "true"
      NGINX_CONTAINER: "hello_django_nginx_stage"

  newman:
    build: ./newman
    image: hello_django_newman
    container_name: hello_django_newman_stage
    entrypoint: ["/home/hello_django/entrypoint.sh"]
    network_mode: "host"
  